version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'twitchbot-rabbitmq'
    hostname: 'rabbitmq'
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/home/arkansweet/rabbitmq/lib
        - ~/.docker-conf/rabbitmq/log/:/home/arkansweet/rabbitmq/log
    networks:
        - internal_network
  postgres:
    image: postgres:10.5
    container_name: 'twitchbot-postgres'
    hostname: 'postgres'
    restart: always
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    logging:
        options:
          max-size: 10m
          max-file: "3"
    ports:
        - '5432:5432'
    volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
        - internal_network
  #core:
    #image: twitchbot:0.1
    #ports:
        #- '8080:8080'
        #- '443:443'
    #restart: always
    #networks:
        #- internal_network
networks:
  internal_network:
    ipam:
        driver: default
        config:
            - subnet: "172.24.24.0/24"
    
    
